apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fzx9ibzxq-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6d79b041ed.puy2.p3.openshiftapps.com/rhtap/rhtap-qe:f638809959a82a360b320b731ffba525cacb6adf@sha256:8abdb658ddd01019a662b830d3db44d3f2cf23f8b9c518949cd2c1d0ed182cc1
          name: container-image
