apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fzx9ibzxq-nodejs 
  janus-idp.io/tekton: fzx9ibzxq-nodejs
  backstage.io/kubernetes-id: fzx9ibzxq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fzx9ibzxq-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  